package weekly

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

type observedTime struct {
	Seconds        int64
	Nanoseconds    uint32
	Whole, Precise string
	WindowStart    string `json:"window_start"`
}

func checkTime(t *testing.T, actual Timestamp, expected *observedTime) {
	t.Helper()
	if expected == nil {
		t.Fatal("unexpected timestamp")
	}
	if actual.Seconds != expected.Seconds || actual.Nanoseconds != expected.Nanoseconds || actual.Format(false) != expected.Whole || actual.Format(true) != expected.Precise || actual.WindowStart().Format(true) != expected.WindowStart {
		t.Fatalf("time=%+v %s %s window=%s expected=%+v", actual, actual.Format(false), actual.Format(true), actual.WindowStart().Format(true), expected)
	}
}

func TestOriginalRustWeeklyParsing(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "tests", "migration", "storage", "weekly-vectors.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Cases []struct {
			Kind, Input string
			Output      struct {
				Valid     bool
				Timestamp *observedTime
				Manifest  *struct {
					DbName    string  `json:"db_name"`
					RunId     *string `json:"run_id"`
					Timestamp *observedTime
					Ids       []string
				}
			}
		}
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	for index, scenario := range fixture.Cases {
		t.Run(scenario.Kind+"/"+strconv.Itoa(index), func(t *testing.T) {
			if scenario.Kind == "date" {
				stamp, ok := ParseTimestamp(scenario.Input)
				if ok != (scenario.Output.Timestamp != nil) {
					t.Fatalf("acceptance differs for %q", scenario.Input)
				}
				if ok {
					checkTime(t, stamp, scenario.Output.Timestamp)
				}
				return
			}
			if runtime.GOOS != "windows" && strings.Contains(scenario.Input, `\\`) {
				t.Skip("host-platform basename vector generated by Windows Rust")
			}
			actual, err := ParseManifest([]byte(scenario.Input))
			if (err == nil) != scenario.Output.Valid {
				t.Fatalf("JSON acceptance differs: %v input=%s", err, scenario.Input)
			}
			if err != nil {
				return
			}
			expected := scenario.Output.Manifest
			if (actual == nil) != (expected == nil) {
				t.Fatalf("publication presence differs: actual=%+v expected=%+v", actual, expected)
			}
			if actual == nil {
				return
			}
			ids := make([]string, len(actual.ArticleIds))
			for index, id := range actual.ArticleIds {
				ids[index] = strconv.FormatInt(id, 10)
			}
			if actual.DbName != expected.DbName || !reflect.DeepEqual(actual.RunId, expected.RunId) || !reflect.DeepEqual(ids, expected.Ids) {
				t.Fatalf("manifest=%+v expected=%+v", actual, expected)
			}
			checkTime(t, actual.GeneratedAt, expected.Timestamp)
		})
	}
}
