//! Export synthetic Rust observations for independent Go compatibility tests.
//!
//! All credentials in this executable are public test constants. Outputs are written
//! only beneath a newly created, marker-guarded operating-system temporary root.

use std::error::Error;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use litradar_auth::{hash_legacy_password, hash_token, is_valid_new_password, verify_password};
use litradar_domain::ids::{stable_sqlite_id, ArticleId, JournalId};
use litradar_storage::secrets::SecretCodec;
use litradar_storage::{migrate_auth_database, open_sqlite_connection};
use serde_json::{json, Value};

const MARKER: &str = ".litradar-migration-fixture";
const MARKER_CONTENT: &str = "litradar-migration-fixture-v1\n";
const FIXTURE_TIME: f64 = 1_700_000_000.0;
const FIXTURE_PASSWORD: &str = "MigrationFixture!2026";
const FIXTURE_SALT: &str = "migration-fixture-salt";
const FIXTURE_KEY: [u8; 32] = [42; 32];
const CURRENT_PHC: &str = "$argon2id$v=19$m=19456,t=2,p=1$bGl0cmFkYXItZHVtbXkhIQ$ZYJd4/sBFG46tq7/498a19Zgzc/4MglD6AaOL5G1bdM";

/// Run the explicitly requested synthetic export and report failures without secret values.
fn main() {
    if let Err(error) = run() {
        eprintln!("migration fixture export failed: {error}");
        std::process::exit(1);
    }
}

/// Validate one output root, generate fixtures, and emit a bounded public result.
fn run() -> Result<(), Box<dyn Error>> {
    let arguments: Vec<_> = std::env::args_os().skip(1).collect();
    if arguments.len() != 1 {
        return Err(io::Error::other("usage: migration_fixture GUARDED_TEMP_ROOT").into());
    }
    let root = validate_root(Path::new(&arguments[0]))?;
    let destination = root.join("fixtures");
    fs::create_dir(&destination)?;
    fs::write(
        destination.join("openapi.json"),
        litradar_api::generated_openapi_json()?,
    )?;
    write_json(&destination.join("crypto.json"), &crypto_vectors()?)?;
    write_json(
        &destination.join("identifiers.json"),
        &json!({
            "article": ArticleId(i64::MAX),
            "journal": JournalId(9_007_199_254_740_993),
            "stable": (["", "migration-fixture", "中文期刊"].map(|value| json!({
                "input": value,
                "prefix": "article",
                "expectedDecimal": stable_sqlite_id(value, "article").to_string()
            })))
        }),
    )?;
    export_auth(&destination)?;
    let content = destination.join("content.sqlite");
    drop(litradar_index::schema::open_content_db(&content)?);
    write_json(
        &destination.join("content-schema.json"),
        &schema_snapshot(&content)?,
    )?;
    let control = destination.join("control.sqlite");
    drop(litradar_index::control::open_control_db(&control)?);
    write_json(
        &destination.join("control-schema.json"),
        &schema_snapshot(&control)?,
    )?;
    export_historical_auth(&destination)?;
    fs::write(
        destination.join("content-schema.sql"),
        litradar_storage::index_schema::INDEX_CONTENT_TABLES_SQL,
    )?;
    println!(
        "{}",
        json!({"format": "litradar-migration-fixture-v1", "synthetic": true})
    );
    Ok(())
}

/// Refuse arbitrary directories, links, invalid markers and reuse of existing fixture data.
fn validate_root(path: &Path) -> Result<PathBuf, Box<dyn Error>> {
    let metadata = fs::symlink_metadata(path)?;
    if !metadata.is_dir() || metadata.file_type().is_symlink() {
        return Err(io::Error::other("fixture root must be a real directory").into());
    }
    let root = fs::canonicalize(path)?;
    let temporary = fs::canonicalize(std::env::temp_dir())?;
    if root == temporary || !root.starts_with(temporary) {
        return Err(
            io::Error::other("fixture root must be below the OS temporary directory").into(),
        );
    }
    let marker = root.join(MARKER);
    let metadata = fs::symlink_metadata(&marker)?;
    if !metadata.is_file()
        || metadata.file_type().is_symlink()
        || fs::read_to_string(marker)? != MARKER_CONTENT
    {
        return Err(io::Error::other("invalid fixture marker").into());
    }
    if root.join("fixtures").exists() {
        return Err(io::Error::other("fixture output already exists").into());
    }
    Ok(root)
}

/// Serialize one observed result with an explicit final newline.
fn write_json(path: &Path, value: &Value) -> Result<(), Box<dyn Error>> {
    let mut bytes = serde_json::to_vec_pretty(value)?;
    bytes.push(b'\n');
    fs::write(path, bytes)?;
    Ok(())
}

/// Capture public cryptographic behavior; random-nonce envelopes are frozen once, never regenerated by Go.
fn crypto_vectors() -> Result<Value, Box<dyn Error>> {
    let codec = SecretCodec::from_key(FIXTURE_KEY);
    let contexts = [
        "notification_settings:2:ai_api_key",
        "runtime_settings:provider_proxy_url",
        "cnki_sessions:2:session_json",
    ];
    let mut envelopes = Vec::new();
    for context in contexts {
        let plaintext = "synthetic-only-凭据";
        let envelope = codec.encrypt(plaintext, context)?;
        envelopes.push(json!({
            "context": context, "plaintext": plaintext, "envelope": envelope,
            "decrypted": codec.decrypt(&envelope, context)?,
            "wrongContextRejected": codec.decrypt(&envelope, "wrong-context").is_err(),
            "wrongKeyRejected": SecretCodec::from_key([43; 32]).decrypt(&envelope, context).is_err()
        }));
    }
    Ok(json!({
        "syntheticOnly": true, "keyByteRepeated32Times": 42,
        "legacy": {"password": "secret123", "salt": "salt",
            "hash": hash_legacy_password("secret123", "salt")},
        "token": {"input": "token", "hash": hash_token("token")},
        "current": {"password": "litradar-auth-dummy-password", "phc": CURRENT_PHC,
            "result": format!("{:?}", verify_password("litradar-auth-dummy-password", "", CURRENT_PHC)),
            "wrongPassword": format!("{:?}", verify_password("incorrect", "", CURRENT_PHC)),
            "wrongParameters": format!("{:?}", verify_password("litradar-auth-dummy-password", "", &CURRENT_PHC.replace("m=19456", "m=19457")))},
        "passwordPolicy": (["12345678901", "123456789012", "😀😀😀😀😀😀😀😀😀😀😀", "😀😀😀😀😀😀😀😀😀😀😀😀"].map(|password| json!({"input": password, "accepted": is_valid_new_password(password)}))),
        "envelopes": envelopes,
        "cleared": codec.decrypt("", "any-context")?,
        "plaintextRejected": codec.decrypt("not-an-envelope", "any-context").is_err(),
        "malformedRejected": codec.decrypt("litradarenc:v1:invalid:invalid", "any-context").is_err()
    }))
}

/// Build deterministic account rows and record actual runtime-setting serialization.
fn export_auth(destination: &Path) -> Result<(), Box<dyn Error>> {
    let database = destination.join("auth.sqlite");
    migrate_auth_database(&database)?;
    let password_hash = hash_legacy_password(FIXTURE_PASSWORD, FIXTURE_SALT);
    let administrator = litradar_storage::bootstrap_admin(
        &database,
        "migration_admin",
        &password_hash,
        FIXTURE_SALT,
        FIXTURE_TIME,
    )?;
    litradar_storage::create_invite_code(
        &database,
        administrator.id,
        "migration-invite",
        FIXTURE_TIME,
    )?;
    let member = litradar_storage::register_user_with_invite(
        &database,
        "migration_member",
        &password_hash,
        FIXTURE_SALT,
        Some("migration-invite"),
        FIXTURE_TIME + 1.0,
    )?;
    litradar_storage::insert_personal_access_token(
        &database,
        member.id,
        &hash_token("migration-synthetic-access-token"),
        "migration-fixture",
        FIXTURE_TIME + 3600.0,
        FIXTURE_TIME + 2.0,
    )?;
    write_json(
        &destination.join("auth-schema.json"),
        &schema_snapshot(&database)?,
    )?;
    write_json(
        &destination.join("runtime-settings.json"),
        &serde_json::to_value(litradar_storage::list_runtime_settings(
            &database,
            &SecretCodec::from_key(FIXTURE_KEY),
        )?)?,
    )?;
    write_json(
        &destination.join("auth-rows.json"),
        &json!({
            "administratorId": administrator.id.value(), "memberId": member.id.value(),
            "createdAt": FIXTURE_TIME, "legacyHash": password_hash,
            "salt": FIXTURE_SALT, "password": FIXTURE_PASSWORD, "syntheticOnly": true
        }),
    )?;
    Ok(())
}

/// Capture declared schema, native SQLite identity and ordered schema text without dumping FTS shadow data.
fn schema_snapshot(path: &Path) -> Result<Value, Box<dyn Error>> {
    let connection = open_sqlite_connection(path)?;
    let version = connection.query_row("PRAGMA user_version", [], |row| row.get::<_, i64>(0))?;
    let sqlite =
        connection.query_row("SELECT sqlite_version()", [], |row| row.get::<_, String>(0))?;
    let mut statement = connection
        .prepare("SELECT type, name, tbl_name, sql FROM sqlite_schema ORDER BY type, name")?;
    let rows = statement.query_map([], |row| {
        Ok(json!({
            "type": row.get::<_, String>(0)?, "name": row.get::<_, String>(1)?,
            "table": row.get::<_, String>(2)?, "sql": row.get::<_, Option<String>>(3)?
        }))
    })?;
    let mut schema = Vec::new();
    for row in rows {
        schema.push(row?);
    }
    Ok(json!({"userVersion": version, "sqliteVersion": sqlite, "objects": schema}))
}

/// Preserve the existing version19 scheduler history regression before and after the real migration.
fn export_historical_auth(destination: &Path) -> Result<(), Box<dyn Error>> {
    let database = destination.join("auth-v19.sqlite");
    migrate_auth_database(&database)?;
    let connection = open_sqlite_connection(&database)?;
    connection.execute_batch(
        "DROP TABLE scheduled_task_runs;
         CREATE TABLE scheduled_task_runs (
             id INTEGER PRIMARY KEY AUTOINCREMENT, task_id INTEGER NOT NULL,
             task_name TEXT NOT NULL, scheduled_for INTEGER NOT NULL,
             status TEXT NOT NULL CHECK(status IN ('pending','claimed','running','success',
                 'failed','timed_out','error','unknown','cancelled')),
             worker_id TEXT, claim_expires_at REAL, claimed_at REAL, started_at REAL,
             finished_at REAL, output_summary TEXT NOT NULL DEFAULT '',
             UNIQUE(task_id, scheduled_for));
         INSERT INTO scheduled_task_runs (id,task_id,task_name,scheduled_for,status)
             VALUES(9,99,'Deleted fixture task',600,'unknown');
         INSERT INTO scheduled_task_runs (id,task_id,task_name,scheduled_for,status)
             VALUES(1000,99,'Deleted fixture task',10000,'success');
         DELETE FROM scheduled_task_runs WHERE id=1000;
         PRAGMA user_version=19;",
    )?;
    connection.execute(
        "VACUUM INTO ?1",
        [destination
            .join("auth-v19-input.sqlite")
            .to_string_lossy()
            .as_ref()],
    )?;
    drop(connection);
    write_json(
        &destination.join("auth-v19-before.json"),
        &schema_snapshot(&database)?,
    )?;
    migrate_auth_database(&database)?;
    write_json(
        &destination.join("auth-v19-after.json"),
        &schema_snapshot(&database)?,
    )?;
    let connection = open_sqlite_connection(&database)?;
    let row = connection.query_row(
        "SELECT id,scheduled_for,status,trigger_kind FROM scheduled_task_runs",
        [],
        |row| {
            Ok(
                json!({"id": row.get::<_, i64>(0)?, "scheduledFor": row.get::<_, i64>(1)?,
            "status": row.get::<_, String>(2)?, "triggerKind": row.get::<_, String>(3)?}),
            )
        },
    )?;
    let sequence = connection.query_row(
        "SELECT seq FROM sqlite_sequence WHERE name='scheduled_task_runs'",
        [],
        |row| row.get::<_, i64>(0),
    )?;
    write_json(
        &destination.join("auth-v19-result.json"),
        &json!({"row": row, "sequence": sequence}),
    )
}
